apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.111.107.146
  environments:
  - key: dev
    owner: twotired
    repository: twotired-jx3-minikube-desktop
  - key: staging
  - key: production
  ingress:
    domain: 192.168.39.211.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: twotired
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
