filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/go-http-desktop
  version: 0.0.2
  name: go-http-desktop
  values:
  - jx-values.yaml
- chart: dev/python-http-desktop
  version: 0.0.2
  name: python-http-desktop
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
